version: '3.8'

services:
  admin:
    image: admin
    container_name: admin
    build:
      context: .
      dockerfile: Dockerfile.Admin
    ports:
      - "3024:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - public_network
      - internal_network

  identity:
    image: identity
    container_name: identity
    depends_on:
      - rabbitmq
    ports:
      - "2023:80"
    build:
      context: .
      dockerfile: Dockerfile.Identity
    networks:
      - internal_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  identity_db:
    image: postgres:latest
    container_name: identity_db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - identity_db_data:/var/lib/postgresql/data/
    networks:
      - public_network
      - internal_network

  course:
    image: course
    container_name: course
    depends_on:
      - rabbitmq
    ports:
      - "2024:80"
    build:
      context: .
      dockerfile: Dockerfile.Course
    networks:
      - internal_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  course_db:
    image: postgres:latest
    container_name: course_db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - course_db_data:/var/lib/postgresql/data/
    networks:
      - internal_network
      - public_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - public_network
      - internal_network

volumes:
  identity_db_data:
  course_db_data:

networks:
  internal_network:
    internal: true
  public_network:
