services:
  identity:
    image: identity
    container_name: identity
    depends_on:
         - rabbitmq
         - identity_db1      
    build:
        context: .
        dockerfile: Dockerfile.Identity
    ports:
        - '2023:80'
  identity_db1:
    image: postgres:latest
    container_name: identity_db1
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - identity_db1_data:/var/lib/postgresql/data/
  course:
    image: course
    container_name: course
    depends_on: 
        - rabbitmq
        - course_db
    build:
        context: .
        dockerfile: Dockerfile.Course
    ports:
        - '2024:80'
  course_db:
    image: postgres:latest
    container_name: course_db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - course_db_data:/var/lib/postgresql/data/
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - internal
networks:
  internal:
volumes: 
  identity_db1_data:
  course_db_data:
